### PR TITLE
Don't use an anonymous function for the escape option

### PR DESCRIPTION
**Pull request by evanpurkhiser**
The escape option must be of type `callable`, since the anonymous function was just calling the `HTML::chars` method we can instead just pass an array representing this method and it will be seen as a callable type

See: http://php.net/manual/en/language.types.callable.php

### CODE REVIEW

**Comment by zombor** [comment]
This is functionally the same, eh? Why bother changing it?

**Comment by evanpurkhiser** [comment]
I suppose just because it's slightly cleaner. Nothing to tag a new version over though.

**Comment by evanpurkhiser** [comment]
Would you like me to target this at `develop` while I'm at it as well?

**Comment by evanpurkhiser** [comment]
Hey @zombor, I'm going through all my open PRs to see if I can get a resolution on them. Any chance of seeing this small change merged in? Or should I just go ahead and close it?

Sorry for the bother. Thanks!

**Comment by zombor** [comment]
I think I actually prefer the existing code, as it reveals it's intentions better.

**Comment by shadowhand** [comment]
@zombor Agree.

**Comment by evanpurkhiser** [comment]
Thanks guys, appreciate the resolution!

**Pull request closed without merging**
