### PR TITLE
Update to KOstache/guide/kostache/usage.md

### PR DESCRIPTION
**Pull request by aaronsofaly**
Not a big change but I thought it would clear any confusion as to needing to use {{>content}} instead of {{>body}}.

### CODE REVIEW

**Comment by aaronsofaly** [comment]
oops, the whole .gitignore part can be ignored...

**Comment by zombor** [comment]
This was already fixed by a723ef519c8fc2e8b62a4795add388223015a0b0.

**Comment by aaronsofaly** [comment]
That commit changed the README.markdown file, however, the issue still persists in the usage.md file.  This pull request fixes the discrepancy between those two files.

**Comment by zombor** [comment]
Ah, sorry, missed that. Can you retarget this for the develop branch?

**Pull request closed without merging**
