### PR TITLE
Need to echo, or nothing is rendered.

### PR DESCRIPTION
**Pull request by ddrake**
Ref: http://forum.kohanaframework.org/discussion/comment/57183#Comment_57183

Some users may also find it useful to turn on MustacheExceptions for UNKNOWN_VARIABLE and UNKNOWN_PARTIAL in vendor/mustache/Mustache.php

### CODE REVIEW

**Comment by shadowhand** [comment]
Actually the correct solution is to replace `text()` with `handle()`.

**Comment by ddrake** [comment]
If you say so, it must be.  But when I tested I found the following:
Kohana_Exception::handle($e) throws an exception of its own (call to undefined method)
Kohana_Exception::handler($e) renders nothing
echo Kohana_Exception:handler($e) renders nothing
echo Kohana_Exception:text($e) renders a short message

an easy way to test is to add a (#) pound sign to a tag that shouldn't have one.

**Comment by shadowhand** [comment]
Use Kohana exception ::handler() rather than just ::text() to display the exception, closed by cf6882212117a5435be5dcd482ae57eabdd984ff

**Comment by shadowhand** [comment]
I'm not sure how you are testing that, but `Kohana_Exception::handler()` will output a message. Within `render()`, we capture the output using `ob_start()` and return it rather than displaying it. My tests confirm that this is the correct fix.

**Comment by ddrake** [comment]
You're right.  I understand it now.   :-)   I was being a bit too DRY for my own good.  My custom error handler was using the same Kostache layout that I was purposely trying to break for testing purposes.  When I used handler(), the stack just filled up with exceptions and nothing was rendered.

**Pull request closed without merging**
