### PR TITLE
Bump Mustache version to v0.8.0.

### PR DESCRIPTION
**Pull request by lukemorton**
Up the Mustache version to include dot notation by default plus some other improvements. Has been working fine for me on Kohana 3.2 for a while now.

### CODE REVIEW

**Comment by Austinb** [comment]
Is there any ETA on this happening?

One note when you do update to this version of Mustache it will error out on you if you have mustache files with {{%DOT-NOTATION}} included.  You will have to remove them all or you will get MustacheExceptions.

**Comment by lukemorton** [comment]
Good point on the dot-notation pragma. I've not actually used it until it was placed in the official spec but I assume there might be some people out there. Perhaps this should break into a 3.2/develop and 3.2/master release?

**Comment by zombor** [comment]
I need to figure out how to do versions. For example, the 3.1 branch is also compatible with 3.2. I'm leaning to only supporting the latest kohana version.

**Comment by Austinb** [comment]
IMO if you want to have multiple versions running around I would make a new branch for each.  Other option like you said is to only support the latest version of Kohana.

Something like kohana3.2.x vs kohana3.1.x

**Comment by zombor** [comment]
That's how it's done now, but the 3.1 branch would be the same as the 3.2 branch, there's no difference.

**Comment by Austinb** [comment]
Well you could make a 3.2/master & 3.2/develop and then just merge back into the 3.1 versions until at some point 3.1 will no longer support changes.  Its a bit more work for each release iteration but allows you to keep both with only working in one of them (i.e. 3.2/master).  Could drop 3.1/develop too. 

Based on how kostache is written now it should support Kohana 3 for awhile.

**Comment by lukemorton** [comment]
Just to stop people asking I would go with what Austinb said. Develop for 3.2/develop and 3.2/master and simply merge them back to 3.1/*. That way people won't start asking questions about the missing version and if they look closer they will see it's always just a merge from 3.2/* branches.

**Comment by zombor** [comment]
I'm just going to support the latest version of kohana.

**Comment by zombor** [comment]
This is fixed by 8e4228c.

**Pull request closed without merging**
