### PR TITLE
Userguide Documentation

### PR DESCRIPTION
**Pull request by slacker**
Includes the render_layout property and documentation for the userguide module, but http://dev.kohanaframework.org/issues/3221 has to be addressed for the documentation to not throw an error.

### CODE REVIEW

**Comment by slacker** [comment]
I merged my branch master into branch dev.  I assume I will need to open a new pull request.  Thanks.

**Comment by zombor** [comment]
Can you break the render_layout into it's own commit? I'd like to pull that in, but not the docs. With the reformatted docs module, I'm going to wait on that.

Also, it should be in it's own branch.

**Comment by slacker** [comment]
Been really busy, but I will do this later this weekend or so.

**Comment by shadowhand** [comment]
Please rebase your changes and replace all references to `View_Layout` with `Kostache_Layout` and remove the actual `View_Layout` class from your branch entirely. If you can get this down to just docs, it will be merged immediately.

**Pull request closed without merging**
