### PR TITLE
Issue #12 Assign literal partials pull request

### PR DESCRIPTION
**Pull request by czukowski**
Ticket URL: https://github.com/zombor/KOstache/issues#issue/12

### CODE REVIEW

**Comment by shadowhand** [comment]
I think this absolutely the wrong way to do it. You should assign the partials manually by overloading `__construct` and assigning them after calling `parent::__construct`. The entire point of Kostache v2 is to prevent this kind of mix and match.

**Comment by czukowski** [comment]
I am doing that in constructor, after `parent::__construct`, but I delegate it to a forms helper class, which generates partials for me and thus requires a public method.

What exactly you think is wrong, using the same function for both or using literal partials altogether? If the former is the case, I don't really insist on having one method for all, but then it would be logical to add another one for literal partials, with a well-thought of name, which I couldn't come up with yet (if we have one named `partial`, then the other would be... what?)

**Comment by shadowhand** [comment]
I think mixing and matching literal and path partials is a terrible idea, its why zombor and I did Kostache v2. zombor and I talked about this yesterday and decided that the scope of mustache is to only support path-based partials. At this time, we will not be accepting this feature.

**Comment by czukowski** [comment]
No sweat. What I don't get though, is that you're saying that the scope of mustache is to only support path-based partials. But Mustache operates with literal partials only and even KOstache loads them from files immediately and keeps them that way in its own property.

Could you explain how bad it is to load a template externally, wrap it into a conditional block and add this string to Mustache as a partial?

**Pull request closed without merging**
