### PR TITLE
Throw Kohana_Exception when Mustache template file not found

### PR DESCRIPTION
**Pull request by anroots**
Was trying to use the module for the first time and ran into `ErrorException [ Warning ]: file_get_contents(): Filename cannot be empty`. Thought that throwing an exception with the path would be more informative <del>(and catchable?)</del>.

### CODE REVIEW

**Comment by zombor** [comment]
Can you put the bracket on a new line? :)

Not sure why this can't be automatically merged...

**Comment by anroots** [comment]
Put the braces on a new line, as per Kohana coding standards.

**Comment by evanpurkhiser** [comment]
I actually think the Kohana coding standards dictate that when throwing an exception (or breaking normal execution in general) with a one line if statement, no braces should be used

See: http://kohanaframework.org/3.3/guide/kohana/conventions#single-line-statements

**Comment by anroots** [comment]
Indeed they do (and as I've seen in the framework and many 3rd party modules code).

I wrap everything in braces (one-line `if`s) due to personal preference for consistency, safety and clarity.

The standards say _should_ so I guess it's allowed?

**Comment by zombor** [comment]
Either way is fine with me. Just leave it as is.

**Comment by shadowhand** [comment]
`ErrorException` can be caught, just like every other PHP error in Kohana. We translate error messages into exceptions for exactly this reason.

**Comment by zombor** [comment]
I think the concern is the message not the exception type.

**Comment by shadowhand** [comment]
> Thought that throwing an exception with the path would be more informative (and catchable?).

The path can be see in the stack trace. `ErrorException` is already catchable. I'm not necessarily opposed to this change, but I do not approve of wording of the issue, because what is being reported is not-a-bug. Please update the description of the commit before merging.

**Comment by anroots** [comment]
Deleted the bit about not being able to catch ErrorException, this was something I overlooked and also not the point of this request. "The point" is to provide a clearer message to (new) users of the module so that the problem could be fixed faster.

**Pull request merged**
